//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerPersona
    {
        public int ID { get; set; }
        public string Stage { get; set; }
        public string Goals { get; set; }
        public string Budget { get; set; }
    }
}
