//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public int CenterID { get; set; }
        public int CompanyID { get; set; }
        public string CenterName { get; set; }
        public string CenterAddress1 { get; set; }
        public string CenterAddress2 { get; set; }
        public string CenterCity { get; set; }
        public string CenterState { get; set; }
        public string CenterCountry { get; set; }
    }
}
