//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocation
    {
        public int CompanyLocationID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddressLine1 { get; set; }
        public string CompanyAddressLine2 { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyZipCode { get; set; }
        public string CompanyLocationPhone { get; set; }
        public Nullable<decimal> CompanyLatitude { get; set; }
        public Nullable<decimal> CompanyLongitude { get; set; }
        public int CompanyID { get; set; }
    }
}
