//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public int IndividualFrom { get; set; }
        public int IndividualTo { get; set; }
        public System.DateTime ConnectRequestDate { get; set; }
        public System.DateTime ConnectAcceptDate { get; set; }
        public string ConnectStatus { get; set; }
    }
}
