//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CardBossEntities1 : DbContext
    {
        public CardBossEntities1()
            : base("name=CardBossEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<CenterFunction> CenterFunctions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAdmin> CompanyAdmins { get; set; }
        public virtual DbSet<CompanyFunction> CompanyFunctions { get; set; }
        public virtual DbSet<CompanyLocation> CompanyLocations { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryProduct> DeliveryProducts { get; set; }
        public virtual DbSet<DeliveryProductTracingUpdateRequest> DeliveryProductTracingUpdateRequests { get; set; }
        public virtual DbSet<DeliveryUnit> DeliveryUnits { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventFunction> EventFunctions { get; set; }
        public virtual DbSet<IndividualCompanyHistory> IndividualCompanyHistories { get; set; }
        public virtual DbSet<IndividualInterest> IndividualInterests { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Privacy> Privacies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCompanyDemandUpdateRequest> ProductCompanyDemandUpdateRequests { get; set; }
        public virtual DbSet<ProductCompanySupply> ProductCompanySupplies { get; set; }
        public virtual DbSet<ProductCompanySupplyUpdateRequest> ProductCompanySupplyUpdateRequests { get; set; }
        public virtual DbSet<ProductDestination> ProductDestinations { get; set; }
        public virtual DbSet<ProductDestinationLeadTime> ProductDestinationLeadTimes { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterials { get; set; }
        public virtual DbSet<ProductReplacement> ProductReplacements { get; set; }
        public virtual DbSet<ProductTotalDemand> ProductTotalDemands { get; set; }
        public virtual DbSet<ProductTracingUpdateRequest> ProductTracingUpdateRequests { get; set; }
        public virtual DbSet<ProductUnitTracing> ProductUnitTracings { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<ResellLevel> ResellLevels { get; set; }
        public virtual DbSet<ResellUpdateRequest> ResellUpdateRequests { get; set; }
        public virtual DbSet<ShareList> ShareLists { get; set; }
        public virtual DbSet<ShortageLevel> ShortageLevels { get; set; }
        public virtual DbSet<ShortageUpdateRequest> ShortageUpdateRequests { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<StorageCategory> StorageCategories { get; set; }
        public virtual DbSet<StorageUnit> StorageUnits { get; set; }
        public virtual DbSet<StorageUnitCategory> StorageUnitCategories { get; set; }
        public virtual DbSet<SupplierCompany> SupplierCompanies { get; set; }
        public virtual DbSet<SupplierInvite> SupplierInvites { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<RiskAlert> RiskAlerts { get; set; }
        public virtual DbSet<ProductCompany> ProductCompanies { get; set; }
        public virtual DbSet<ProductCompanyDemand> ProductCompanyDemands { get; set; }
        public virtual DbSet<ProfilePic> ProfilePics { get; set; }
        public virtual DbSet<FunctionLookup> FunctionLookups { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<GraphConnection> GraphConnections { get; set; }
        public virtual DbSet<GraphNode> GraphNodes { get; set; }
        public virtual DbSet<GreenCompany> GreenCompanies { get; set; }
        public virtual DbSet<GreenFunctionAverage> GreenFunctionAverages { get; set; }
        public virtual DbSet<GreenReco> GreenRecoes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsMap> NewsMaps { get; set; }
        public virtual DbSet<CompanyProductGraph> CompanyProductGraphs { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<ExcelPath> ExcelPaths { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorMessage> VendorMessages { get; set; }
        public virtual DbSet<ProductInfo> ProductInfoes { get; set; }
        public virtual DbSet<ExpertMessage> ExpertMessages { get; set; }
        public virtual DbSet<Expert1> Expert1 { get; set; }
        public virtual DbSet<Professional> Professionals { get; set; }
        public virtual DbSet<Bio> Bios { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<MonitorProduct> MonitorProducts { get; set; }
        public virtual DbSet<MonStatu> MonStatus { get; set; }
    
        public virtual int InitializeCompanyProductDemand(Nullable<int> companyid, Nullable<int> productid)
        {
            var companyidParameter = companyid.HasValue ?
                new ObjectParameter("companyid", companyid) :
                new ObjectParameter("companyid", typeof(int));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InitializeCompanyProductDemand", companyidParameter, productidParameter);
        }
    }
}
