//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryProductTracingUpdateRequest
    {
        public int DeliveryProductTracingUpdateRequestID { get; set; }
        public int DeliveryUnitID { get; set; }
        public int ProductUnitID { get; set; }
        public int CompanyID { get; set; }
        public int IndividualID { get; set; }
        public string RequestStatus { get; set; }
    }
}
