//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryID { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> DeliveryLimitLatitude1 { get; set; }
        public Nullable<int> DeliveryLimitLongitude1 { get; set; }
        public Nullable<int> DeliveryLimitLatitude2 { get; set; }
        public Nullable<int> DeliveryLimitLongitude2 { get; set; }
        public Nullable<int> DeliveryLimitLatitude3 { get; set; }
        public Nullable<int> DeliveryLimitLongitude3 { get; set; }
        public Nullable<int> DeliveryLimitLatitude4 { get; set; }
        public Nullable<int> DeliveryLimitLongitude4 { get; set; }
    }
}
