//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryProduct
    {
        public int DeliveryProductID { get; set; }
        public int DeliveryUnitID { get; set; }
        public int ProductUnitID { get; set; }
        public System.DateTime TrackTime { get; set; }
        public string TrackAddress1 { get; set; }
        public string TrackAddress2 { get; set; }
        public string TrackCity { get; set; }
        public string TrackState { get; set; }
        public string TrackCountry { get; set; }
        public int Latitude { get; set; }
        public int Longitude { get; set; }
    }
}
