//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnit
    {
        public int DeliveryUnitID { get; set; }
        public int DeliveryID { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> DeliveryUnitLimitLatitude1 { get; set; }
        public Nullable<int> DeliveryUnitLimitLongitude1 { get; set; }
        public Nullable<int> DeliveryUnitLimitLatitude2 { get; set; }
        public Nullable<int> DeliveryUnitLimitLongitude2 { get; set; }
        public Nullable<int> DeliveryUnitLimitLatitude3 { get; set; }
        public Nullable<int> DeliveryUnitLimitLongitude3 { get; set; }
        public Nullable<int> DeliveryUnitLimitLatitude4 { get; set; }
        public Nullable<int> DeliveryUnitLimitLongitude4 { get; set; }
    }
}
