//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFunction
    {
        public int EventFunctionID { get; set; }
        public int EventID { get; set; }
        public int FunctionID { get; set; }
        public string ImpactLevel { get; set; }
    }
}
