//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelPath
    {
        public int ExcelPathID { get; set; }
        public int CompanyID { get; set; }
        public string ExcelPath1 { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
