//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphNode
    {
        public int GraphNodeID { get; set; }
        public int ChainId { get; set; }
        public string NodeName { get; set; }
        public string Color { get; set; }
        public string Category { get; set; }
    }
}
