//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphConnection
    {
        public int GraphConnectionID { get; set; }
        public int ChainId { get; set; }
        public Nullable<int> SubChainId { get; set; }
        public string NodeNameOne { get; set; }
        public string NodeNameTwo { get; set; }
    }
}
