//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenFunctionAverage
    {
        public int GreenFunctionAverageID { get; set; }
        public int AvgTotalScore { get; set; }
        public int AvgCertificationScore { get; set; }
        public int AvgGreenProductScore { get; set; }
        public int AvgPensionFundInvestmentScore { get; set; }
        public int AvgRenewableElectricitySource { get; set; }
        public int AvgGreenFleetScore { get; set; }
        public int AvgEnergyAuditScore { get; set; }
        public int AvgFoodWastageScore { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
