//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenReco
    {
        public int GreenRecoID { get; set; }
        public int CompanyID { get; set; }
        public int CertificationReco { get; set; }
        public int GreenProductReco { get; set; }
        public int PensionFundInvestmentReco { get; set; }
        public int RenewableElectricityReco { get; set; }
        public int GreenFleetReco { get; set; }
        public int EnergyAuditReco { get; set; }
        public int FoodWastageReco { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
