//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int HolidayID { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public int Federal { get; set; }
        public Nullable<int> Regional { get; set; }
    }
}
