//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorProduct
    {
        public int MonitorProductID { get; set; }
        public string MonitorProductName { get; set; }
        public string Notes { get; set; }
        public string SKU { get; set; }
        public string OtherID { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
