//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonStatu
    {
        public int MonitorStatusID { get; set; }
        public int MonitorProductID { get; set; }
        public string MonitorStatus { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    }
}
