//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public int NewsMapID { get; set; }
        public string NewsBody { get; set; }
        public string NewsImpact { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
    }
}
