//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public string Post1 { get; set; }
        public Nullable<int> Privacy { get; set; }
        public Nullable<int> InterestID { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string imageURL { get; set; }
        public string username { get; set; }
    }
}
