//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int ProductMaterialID { get; set; }
        public int ProductUnitID { get; set; }
        public int MaterialUnitID { get; set; }
        public System.DateTime MinLeadTime { get; set; }
        public System.DateTime MaxLeadTime { get; set; }
        public int MakeOrder { get; set; }
        public Nullable<int> MakeQuantity { get; set; }
        public Nullable<int> MakeQuantityUnit { get; set; }
        public string ProcessCategory { get; set; }
    }
}
