//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCompanyDemand
    {
        public int ProductCompanyDemandID { get; set; }
        public int CompanyID { get; set; }
        public int ProductID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Demand { get; set; }
        public string DemandUnit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int safety { get; set; }
        public int sold { get; set; }
        public int backorder { get; set; }
        public Nullable<int> instock { get; set; }
        public Nullable<System.DateTime> demanddate { get; set; }
    }
}
