//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTotalDemand
    {
        public int ProductTotalDemandID { get; set; }
        public int ProductUnitID { get; set; }
        public int DemandYear { get; set; }
        public int DemandMonth { get; set; }
        public double Demand { get; set; }
        public string DemandUnit { get; set; }
    }
}
