//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string SKU { get; set; }
        public string OtherID { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public string PriceUnit { get; set; }
        public Nullable<int> MinimumOrderQuantity { get; set; }
        public string MOQUnit { get; set; }
        public string Rating { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public string ShelfLifeUnit { get; set; }
        public string ImageURL { get; set; }
    }
}
