//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDestination
    {
        public int ProductDestinationID { get; set; }
        public int ProductUnitID { get; set; }
        public int SupplierCompanyID { get; set; }
        public int DestinationCompanyID { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public double ExpectedLevel { get; set; }
        public string ExpectedLevelUnit { get; set; }
    }
}
