//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDestinationLeadTime
    {
        public int ProductDestinationLeadTimeID { get; set; }
        public int ProductUnitID { get; set; }
        public int DestinationCompanyID { get; set; }
        public int MinLeadTime { get; set; }
        public int MaxLeadTime { get; set; }
    }
}
