//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCompanySupply
    {
        public int ProductCompanySupplyID { get; set; }
        public int CompanyID { get; set; }
        public int ProductID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Supply { get; set; }
        public string SupplyUnit { get; set; }
    }
}
