//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int RecoID { get; set; }
        public System.DateTime RecoTimeStamp { get; set; }
        public string Reco { get; set; }
        public string Reason { get; set; }
    }
}
