//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResellLevel
    {
        public int ResellLevelID { get; set; }
        public int ProductUnitID { get; set; }
        public int CompanyID { get; set; }
        public int ExcessLevel { get; set; }
        public string ExcessLevelUnit { get; set; }
        public System.DateTime ResellLevelTimestamp { get; set; }
    }
}
