//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortageLevel
    {
        public int ShortageLevelID { get; set; }
        public int ProductUnitID { get; set; }
        public int CompanyID { get; set; }
        public int ShortageLevel1 { get; set; }
        public string ShoratgeLevelUnit { get; set; }
        public System.DateTime ResellLevelTimestamp { get; set; }
    }
}
