//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageUnit
    {
        public int StorageID { get; set; }
        public string StorageName { get; set; }
        public Nullable<int> TotalCapacity { get; set; }
        public Nullable<int> AvailableCapacity { get; set; }
        public string StorageAddress1 { get; set; }
        public string StorageAddress2 { get; set; }
        public string StorageCity { get; set; }
        public string StorageState { get; set; }
        public string StorageCountry { get; set; }
        public Nullable<int> StorageLatitude { get; set; }
        public Nullable<int> StorageLongitude { get; set; }
    }
}
