//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBoss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvite
    {
        public int SupplierInviteID { get; set; }
        public string CompanyName { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEmail { get; set; }
        public System.DateTime InviteDate { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> InviteLastSent { get; set; }
        public Nullable<int> InviteCount { get; set; }
        public Nullable<int> InviteAccepted { get; set; }
    }
}
