//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public int ID { get; set; }
        public long EBayItemID { get; set; }
        public string label { get; set; }
        public string value { get; set; }
    }
}
