//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentInventory
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public long EBayItemID { get; set; }
        public string ItemURL { get; set; }
        public string GalleryURL { get; set; }
        public string SellingState { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string BuyerLocation { get; set; }
        public Nullable<double> Sellingprice { get; set; }
        public Nullable<double> ShippingPrice { get; set; }
        public Nullable<System.DateTime> SoldTime { get; set; }
        public Nullable<int> PopulationSupply { get; set; }
        public string Grade { get; set; }
        public string GradingCompany { get; set; }
        public Nullable<int> NumPlayers { get; set; }
        public Nullable<int> CardYear { get; set; }
        public string Design { get; set; }
        public string CardManufacturer { get; set; }
        public string Border { get; set; }
        public string Era { get; set; }
        public string Feature { get; set; }
        public Nullable<int> Licensed { get; set; }
        public Nullable<decimal> AvgPastFiveSellingPrice { get; set; }
        public string Original { get; set; }
        public string Product { get; set; }
        public string League { get; set; }
        public string Player { get; set; }
        public string Season { get; set; }
        public string Series { get; set; }
        public string Team { get; set; }
        public string Sport { get; set; }
        public Nullable<int> WatchCount { get; set; }
        public Nullable<int> HighDemand { get; set; }
        public string Goal { get; set; }
        public Nullable<int> Processed { get; set; }
    }
}
