//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuacoonEntities1 : DbContext
    {
        public QuacoonEntities1()
            : base("name=QuacoonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BorderRef> BorderRefs { get; set; }
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardBuyer> CardBuyers { get; set; }
        public virtual DbSet<CardCompanyRef> CardCompanyRefs { get; set; }
        public virtual DbSet<CardFeatureRef> CardFeatureRefs { get; set; }
        public virtual DbSet<CurrentInventory> CurrentInventories { get; set; }
        public virtual DbSet<DesignRef> DesignRefs { get; set; }
        public virtual DbSet<Era> Eras { get; set; }
        public virtual DbSet<GradingRef> GradingRefs { get; set; }
        public virtual DbSet<HallOfFame> HallOfFames { get; set; }
        public virtual DbSet<InitialTrainingData> InitialTrainingDatas { get; set; }
        public virtual DbSet<InjuryHistory> InjuryHistories { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<Original> Originals { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerStat> PlayerStats { get; set; }
        public virtual DbSet<PriceChangeRef> PriceChangeRefs { get; set; }
        public virtual DbSet<Retirement> Retirements { get; set; }
        public virtual DbSet<RookieCardInfluence> RookieCardInfluences { get; set; }
        public virtual DbSet<TeamRank> TeamRanks { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<TopInventory> TopInventories { get; set; }
        public virtual DbSet<CardDetail> CardDetails { get; set; }
        public virtual DbSet<PlayerGraph> PlayerGraphs { get; set; }
        public virtual DbSet<SoldInventory> SoldInventories { get; set; }
        public virtual DbSet<FilterInventory> FilterInventories { get; set; }
    }
}
