//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialTrainingData
    {
        public int ID { get; set; }
        public Nullable<long> EBayItemID { get; set; }
        public string EbayTitle { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<System.DateTime> SoldTime { get; set; }
        public string Original { get; set; }
        public string Grader { get; set; }
        public string Manufacturer { get; set; }
        public string CardYear { get; set; }
        public string Product { get; set; }
        public string Grade { get; set; }
        public string League { get; set; }
        public string Era { get; set; }
        public string Player { get; set; }
        public string CardAttributes { get; set; }
        public string Season { get; set; }
        public string Series { get; set; }
        public string Team { get; set; }
        public string ItemURL { get; set; }
        public string GalleryURL { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Sport { get; set; }
        public string BuyerLocation { get; set; }
        public Nullable<int> BidderCount { get; set; }
        public string CardNo { get; set; }
    }
}
