//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGraph
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Zero { get; set; }
        public Nullable<decimal> One { get; set; }
        public Nullable<decimal> Two { get; set; }
        public Nullable<decimal> Three { get; set; }
        public Nullable<decimal> Four { get; set; }
        public Nullable<decimal> Five { get; set; }
    }
}
