//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quacoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PlayerEfficiencyRating { get; set; }
        public Nullable<decimal> TrueShootingPerc { get; set; }
        public Nullable<decimal> AssistRatio { get; set; }
        public Nullable<decimal> TurnoverRatio { get; set; }
        public Nullable<decimal> UsageRatio { get; set; }
        public Nullable<decimal> OffensiveReboundRate { get; set; }
        public Nullable<decimal> DefensiveReboundRate { get; set; }
        public Nullable<decimal> ReboundRate { get; set; }
        public Nullable<decimal> ValueAdded { get; set; }
        public Nullable<decimal> EstimatedWinsAdded { get; set; }
    }
}
